---
# Tasks to generate a self-signed certificate

- name: Make the private directory
  file:
    path: "{{ ssl_path }}"
    state: directory
    mode: 0755

- name: Generate the certificate
  shell: |
    OPENSSLDIR=$(openssl version -a | sed -nre 's,^OPENSSLDIR: *"([^"]*)",\1,p')
    openssl req -x509 -newkey rsa:4096 -keyout "{{ ssl_file_prefix }}privkey.pem" -out "{{ ssl_file_prefix }}cert.pem" \
    -days 2 -nodes -subj "/C=GB/O={{ ssl_hostname }} site/CN={{ ssl_hostname }}" \
    -extensions SAN -config <(cat $OPENSSLDIR/openssl.cnf <(printf "[SAN]\nsubjectAltName=DNS:{{ ssl_hostname }}"))
  args:
    executable: /usr/bin/bash

